version: '3.3'

services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./public:/public/assets
    links:
      - app
    ports:
      - 8000:80
  app:
    build: .
    volumes:
      - .:/src
    links:
      - mongodb
    # command: ["sh", "-c", "sleep 10000"]
    command: ["nodemon", "server", "--port", "3000", "--mongo", "mongodb://mongodb:27017/todos"]
  mongodb:
    image: mongo:3.0
    volumes:
      - db-data:/data/db
volumes:
  db-data:
